name: facebook-notification
namespace: quintana
version: 0.0.2
author: Wazo Team
display_name: Facebook Notifier
plugin_format_version: 1
min_wazo_version: 17.16
tags:
  - beta
  - application
homepage: https://github.com/sboily/wazo-facebook-notifier
